### DISCUSSION TITLE
Functions Deployment not working

### DISCUSSION THREAD

**Discussion by dansiegel** [Azure/functions-action#264] [Q&A]
I have had an incredible amount of problems trying to deploy a new .NET 8 Functions app using the v2 SDK.

Despite following the guidance in the [docs](https://learn.microsoft.com/en-us/azure/azure-functions/functions-how-to-github-actions?tabs=linux%2Cdotnet&pivots=method-template) as suggested in #230 I could never get it to work with the publish profile.

I pivoted to using the credentials that azd created for me in my repo and using the azure login task first. This resolved my issue with being able to successfully publish, however the result that I get when deploying is not so successful. After the functions publish from CI none of the actual functions show up in the Azure Portal, while it works as expected when I publish from Visual Studio manually.

```xml
<PackageVersion Include="Microsoft.Azure.Functions.Worker" Version="2.0.0" />
<PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.0.1" />
<PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.1" />
<PackageVersion Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.0" />
<PackageVersion Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
<PackageVersion Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.0.0" />
```

**Comment by mhumud** [comment]
Hello, I don't know if you solved it, but I had the same problem with the deployment. I am using a Linux Consumption Azure function and I used the action on a Github Action workflow, but the deployed function app did not show any functions. I had to manually redeploy it using VSCode Azure extension many times.

However, after trying a couple of different thigs I found the solution. You must add the parameters `remote-build`, `scm-do-build-during-deployment` and `enable-oryx-build` to the step like this:
```
 - name: 'Deploy to Azure Functions'
   uses: Azure/functions-action@v1
   id: deploy-to-function
   with:
        app-name: 'app-name'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_YOURPROFILEUID }}
        remote-build: true
        scm-do-build-during-deployment: true
        enable-oryx-build: true
```
I found it in the same [documentation](https://github.com/Azure/functions-action?tab=readme-ov-file#parameter-reference), but I didn't pay any attention before. I think it should be more clear 💡

Hope it helps,
Miguel
