### ISSUE TITLE
python function code not updated even when github action function apparently deployed correctly

### ISSUE THREAD

**Issue by olguin** [Azure/functions-action#110]
I am using the following github action workflow using azure action to deploy Function app:

```
 - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
```

The log on github shows:
```

Run Azure/functions-action@v1
Successfully parsed SCM credential from old publish-profile format.
Using SCM credential for authentication, GitHub Action will not perform resource validation.
Successfully acquired app settings from function app (with SCM credential)!
Will archive functions into /home/runner/work/_temp/temp_web_package_3142966436625869.zip as function app content
Will use Kudu https://<scmsite>/api/zipdeploy to deploy since publish-profile is detected.
Setting SCM_DO_BUILD_DURING_DEPLOYMENT in Kudu container to false
Update using Client.updateAppSettingViaKudu
Response with status code 204
App setting SCM_DO_BUILD_DURING_DEPLOYMENT propagated to Kudu container
Setting ENABLE_ORYX_BUILD in Kudu container to false
Update using Client.updateAppSettingViaKudu
Response with status code 204
App setting ENABLE_ORYX_BUILD propagated to Kudu container
Package deployment using ZIP Deploy initiated.
Deploy logs can be viewed at https://dtdv-video-index-uspklrodz4yzi.scm.azurewebsites.net/api/deployments/e3314471abfc4719b4b7c385b80a885f/log
Successfully deployed web package to App Service.
Response with status code 204
Response with status code 204
Response with status code 204
```

But when I go to azure portal/Function App and browse the function code it has not being updated.

One Thing I am noticing is that both SCM_DO_BUILD_DURING_DEPLOYMENT and ENABLE_ORYX_BUILD are being propagated as false but I had both set to true in the function app configuration.

Please help
