### ISSUE TITLE
Node Functions App Deploy fails - Internal Server Error (CODE: 500)

### ISSUE THREAD

**Issue by ryanfollmer** [Azure/functions-action#115]
Created a new Azure Function App today on Windows using a consumption plan and am using Azure/functions-action@v1 in our GH action to deploy a nodejs app (12.x). The first deploy worked just fine. We were able to test the deployed function and it was working. We are using WEBSITE_RUN_FROM_PACKAGE = 1 in our application settings.

However, any subsequent deployment attempt fails.

![image](https://user-images.githubusercontent.com/2651539/146291923-056107d1-e353-4ed2-9b08-2cff63bc01a6.png)

Deployment Center Logs produce a single entry "failed" that doesn't provide any other detail about why this fails.

GH Action Yaml (pretty much a straight up copy of the example):
```
env:
  AZURE_FUNCTIONAPP_NAME: LegacyBuildTest    # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '12.x'                     # set this to the node version to use (supports 8.x, 10.x, 12.x)
  NODE_ENV: development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run build-prod --if-present
        npm run test --if-present
        popd
    - name: Azure Functions Action
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_BUILDTEST_PUBLISH_PROFILE }}
```

Function App Id: 32a72a36-92de-42aa-971f-c01e91608d8d
Operation System: Windows
Runtime Version: 3.3.1.0
