### ISSUE TITLE
Azure function action really slow

### ISSUE THREAD

**Issue by hholst80** [Azure/functions-action#120]
The Set up of the following job takes 1:35 MIN.

```yaml
  deploy-functionapp:
    runs-on: self-hosted
    needs: build-functionapp
    container:
      image: mcr.microsoft.com/azure-cli:latest    
    env:
      AZURE_FUNCTIONAPP_NAME: myapp
      AZURE_FUNCTIONAPP_SECRET: ${{ secrets.FUNCTIONAPP_MYAPP }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: functionapp
      - uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_FUNCTIONAPP_SECRET }}
      - uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: app.zip
```

The deployment takes 23 seconds.

All in all it takes 2 minutes to deploy 200 KB of code to azure functions. That's just ridiculous long time in a CI/CD pipeline.

![image](https://user-images.githubusercontent.com/6200749/159671515-8d9cfee9-6627-4ca1-9686-7018d78daa64.png)

Edit:

It also does not seem to be related to container vs. non container environment. Below is without containers where I have installed az-cli on the host.

![image](https://user-images.githubusercontent.com/6200749/159676823-8e181dd3-a1f5-46a4-a70f-cba9be850a31.png)
