### ISSUE TITLE
Triggers are not always synced after deployment (consumption plan)

### ISSUE THREAD

**Issue by kmagusiak** [Azure/functions-action#135]
Hello,

We have migrated from Azure DevOps to using github actions for deployment recently, but after some deployments the functions are not seen in the poral. After clicking on "refresh" button, the functions appear.
![image](https://user-images.githubusercontent.com/1943198/178249074-3bcc943c-a07a-49c9-ae60-bca891a52660.png)

After discussing with Microsoft support, it seems the functions are not synced properly.
Running in debug mode, we see a call to the URL `/providers/Microsoft.Web/sites/{name}/${this._slotUrl}/hostruntime/admin/host/synctriggers`.
The "refresh" button on the web interface calls `/providers/Microsoft.Web/sites/{name}/host/default/sync?api-version=2018-11-01`.
The documentation I was given from Microsoft states that https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/sync-function-triggers should be called.

Technical details:
- python functions deployed with a zip package
- linux
- consumption plan

```
      - name: Azure Functions Action
        uses: Azure/functions-action@v1.4.6
        with:
          app-name: myapp_sfozehfzoe  // just an example
          package: build.zip
```
