### ISSUE TITLE
RBAC auth type with GitHub Open ID Connect

### ISSUE THREAD

**Issue by melzayet** [Azure/functions-action#153]
As "functions-actions" already supports RBAC, is logging to Azure through GitHub Open ID a supported flow?

For example, app service deploy GH action does document the support for Open ID:
https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=openid

Basically,  an Azure login action will use an SP following Open ID connect flow, then web app deploy action will use that SP
<img width="787" alt="Screenshot 2022-09-02 at 18 22 35" src="https://user-images.githubusercontent.com/38279473/188206207-8e299d58-d546-4678-b124-0fe97091a492.png">

Thanks

**Comment by patelchandni** [comment]
Hey @melzayet, the support you are asking for is under a separate task: Azure/login@v1. So, that task will have same behavior across all workflows. Here are some samples: 
1. https://github.com/Azure/login#sample-workflow-that-uses-azure-login-action-using-oidc-to-run-az-powershell-windows
2. https://github.com/Azure/login#sample-workflow-that-uses-azure-login-action-using-oidc-to-run-az-cli-linux

**Comment by melzayet** [comment]
thanks @patelchandni!  Azure/login@v1 already supports workload federated identity, but I wanted to know if  Azure/functions@v1 would support a service principal that was logged in with  Azure/login@v1 using the workload federated identity model

**Comment by Mandur** [comment]
We are also interested in the workload federation identity support

**Comment by tjcorr** [comment]
I think the question here is if I do an Azure/login step beforehand will this action reuse the credentials there to do the publishing without the need for a user to specify a publish-profile?

**Comment by tjcorr** [comment]
I just did a test and was able to deploy using OIDC just fine. Here is a sample of my workflow:

```
on: 
  push:

permissions:
  id-token: write
  contents: read

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Az CLI login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Function Publish
      uses: Azure/functions-action@v1
      with:
        app-name: ....
        package: ...
````
