### ISSUE TITLE
Timeout when deploy Node/Java Functions in linux Azure function

### ISSUE THREAD

**Issue by jlrosende** [Azure/functions-action#162]
When I try to deploy new code to an azure function. With Node or Java code I have a timeout issue.

This happens randomly, and I not able to replicate the error properly.

This is the output of the action. with the error

```
Using RBAC for authentication, GitHub Action will perform resource validation.
Successfully acquired site configs from function app!
Detected function app sku: ***
Successfully acquired app settings from function app (RBAC)!
Detected function app language: Java
Will archive ./code/***/target/azure-functions/*** into /home/runner/work/_temp/temp_web_package_6218868638730215.zip as function app content
Will use https://<scmsite>/api/zipdeploy to deploy since RBAC Azure credential is detected.
Package deployment using ZIP Deploy initiated.
Updating submodules.
Preparing deployment for commit id '5ba10336-1'.
PreDeployment: context.CleanOutputPath False
PreDeployment: context.OutputPath /home/site/wwwroot
Generating deployment script.
Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "/tmp/zipdeploy/extracted" -o "/home/site/deployments/tools" --basic --sitePath "/tmp/zipdeploy/extracted"').
Running deployment command...
Command: "/home/site/deployments/tools/deploy.sh"
Handling Basic Web Site deployment.
Kudu sync from: '/tmp/zipdeploy/extracted' to: '/home/site/wwwroot'
Copying file: 'host.json'
........
.....
......
Finished successfully.
An unknown error has occurred. Check the diagnostic log for details.
Error: Failed to deploy web package to App Service.
Error: Execution Exception (state: PublishContent) (step: Invocation)
Error:   When request Azure resource at PublishContent, zipDeploy : Failed to use /home/runner/work/_temp/temp_web_package_6218868638730215.zip as ZipDeploy content
Error:     Package deployment using ZIP Deploy failed. Refer logs for more details.
Error: Deployment Failed!
```

**Comment by patelchandni** [comment]
@jlrosende , Is it Linux Consumption plan? Can you share your GitHub workflow?
Also, Workflows will change for node and java, and they will have different requirements.

**Comment by jlrosende** [comment]
we are currently deploy node and java funcitons. 

The workflow is simple.

pre-steps:
* checkout
* init java/node version

Then

1. Login in to azure
2. Build our app (node npm o java mvn)
3. Update function configurations
4. Upload the code with this action

I share the code from the java app deployment pipeline.

```yaml
      - name: 🗒️ 'Apply Azure Function Config'
        env:
          FUNCTION_APP_NAME: ${{ inputs.AZURE_FUNCTIONAPP_NAME }}
        run: |
          az functionapp config appsettings set -o none --subscription ${{ env.AZURE_SUBSCRIPTION_ID }} --resource-group ${{ inputs.AZURE_FUNCTIONAPP_RESOURCEGROUP }} --name ${{ inputs.AZURE_FUNCTIONAPP_NAME }} --settings "${{ join(fromJson(steps.azf_settings.outputs.settings), '" "') }}"

        # DEPLOY MVN
      - name: 🚀 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ inputs.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ inputs.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
```
