### ISSUE TITLE
Deployment fails because not enough disk space

### ISSUE THREAD

**Issue by gpmatz** [Azure/functions-action#164]
# info
when i deploy my code to a deploymentslot the deployment fails often because there is not enough space on the disc

I can manually delete the old zip-packages in `C:/home/data/SitePackages/*.zip` and then i can run my github-action again. now the deployment works.

**is it possible to delete the old packages with the deployment?**

or is there a better solution to my problem? 

## code
this is my github action

```yaml
name: Build and deploy Node.js project to Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: 'apppname'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_SLOTNAME: 'dev'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  NODE_VERSION: '18.x'                      # set this to the node version to use (e.g. '8.x', '10.x', '12.x')

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies Using Npm'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run build --if-present
        npm run test --if-present
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        slot-name: ${{ env.AZURE_FUNCTIONAPP_SLOTNAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        respect-funcignore: true
``` 

## LogFile in Kudu
the last entry after a failed deployment says this:
There is not enough space on the disk.

```xml
...
<EventData>
<Data>3006</Data>
<Data>A parser error has occurred.</Data>
<Data>12/6/2022 1:19:01 AM</Data>
<Data>12/6/2022 12:19:01 AM</Data>
...
<Data>Full</Data>
<Data>/</Data>
<Data>
C:\Program Files (x86)\SiteExtensions\Kudu\99.41021.5971\
</Data>
<Data>10-30-2-204</Data>
<Data/>
<Data>5880</Data>
<Data>w3wp.exe</Data>
<Data>IIS APPPOOL\gpjoperations</Data>
<Data>HttpParseException</Data>
<Data>
There is not enough space on the disk. at System.Web.Compilation.AssemblyBuilder.AddBuildProvider(BuildProvider buildProvider) at System.Web.Compilation.BuildProvidersCompiler.ProcessBuildProviders() at System.Web.Compilation.BuildProvidersCompiler.PerformBuild() at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound) at System.Web.Compilation.BuildManager.CreateInstanceFromVirtualPath(VirtualPath virtualPath, Type requiredBaseType, HttpContext context, Boolean allowCrossApp) at System.Web.WebPages.BuildManagerWrapper.CreateInstanceOfType[T](String virtualPath) at System.Web.WebPages.VirtualPathFactoryExtensions.CreateInstance[T](IVirtualPathFactory factory, String virtualPath) at System.Web.WebPages.VirtualPathFactoryManager.CreateInstanceOfType[T](String virtualPath) at System.Web.WebPages.VirtualPathFactoryExtensions.CreateInstance[T](IVirtualPathFactory factory, String virtualPath) at System.Web.WebPages.WebPageHttpHandler.CreateFromVirtualPath(String virtualPath, IVirtualPathFactory virtualPathFactory) at System.Web.WebPages.WebPageRoute.DoPostResolveRequestCache(HttpContextBase context) at System.Web.WebPages.WebPageHttpModule.OnApplicationPostResolveRequestCache(Object sender, EventArgs e) at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) There is not enough space on the disk. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) at System.Web.Compilation.AssemblyBuilder.CreateCodeFileWithAssert(String generatedFilePath) at System.Web.Compilation.AssemblyBuilder.CreateCodeFile(BuildProvider buildProvider, String& filename) at System.Web.Compilation.AssemblyBuilder.AddCodeCompileUnit(BuildProvider buildProvider, CodeCompileUnit compileUnit) at System.Web.WebPages.Razor.AssemblyBuilderWrapper.AddCodeCompileUnit(BuildProvider buildProvider, CodeCompileUnit compileUnit) at System.Web.WebPages.Razor.RazorBuildProvider.GenerateCodeCore(IAssemblyBuilder assemblyBuilder) at System.Web.WebPages.Razor.RazorBuildProvider.GenerateCode(AssemblyBuilder assemblyBuilder) at System.Web.Compilation.AssemblyBuilder.AddBuildProvider(BuildProvider buildProvider)
</Data>
<Data>...
</Data>
<Data>/ProcessExplorer/</Data>
<Data>...</Data>
<Data/>
<Data>False</Data>
<Data/>
<Data>IIS APPPOOL\gpjoperations</Data>
<Data>32</Data>
<Data>IIS APPPOOL\gpjoperations</Data>
<Data>False</Data>
<Data>
</Data>
</EventData>
...
```
