### ISSUE TITLE
Continuous Deployment to functions failing with "Failed to fetch Kudu App Settings. Unauthorized (CODE: 401)

### ISSUE THREAD

**Issue by jeremydvoss** [Azure/functions-action#186]
I set up continuous deployment in resource creation. My networking access restrictions are set to "Allow all." But, I get the following errors when it tries to publish:

`Execution Exception (state: ValidateAzureResource) (step: Invocation)`

`When request Azure resource at ValidateAzureResource, Get Function App Settings : Failed to acquire app settings from https://<scmsite>/api/settings with publish-profile`

`Failed to fetch Kudu App Settings. Unauthorized (CODE: 401)`

`      Error: Failed to fetch Kudu App Settings.
Unauthorized (CODE: 401)
    at Kudu.<anonymous> (/home/runner/work/_actions/Azure/functions-action/v1/lib/appservice-rest/Kudu/azure-app-kudu-service.js:69:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/Azure/functions-action/v1/lib/appservice-rest/Kudu/azure-app-kudu-service.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

![image](https://github.com/Azure/functions-action/assets/4807316/4e5f9e7a-2456-40b5-9e15-d36093f7df91)

Is this related to the [recent issues with pull requests and actions](https://www.githubstatus.com/) or am I missing something I need to do in addition to setting up continuous deployment in the azure portal?

**Comment by runceel** [comment]
I'm facing same issue. My github actions file is:

```yaml
name: .NET Core アプリケーションを関数アプリ fun-mockapitest にビルドしてデプロイする
on:
  push:
    branches:
    - main
env:
  AZURE_FUNCTIONAPP_NAME: fun-mockapitest
  AZURE_FUNCTIONAPP_PACKAGE_PATH: publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: src\CQAKBMaintenanceApi\CQAKBMaintenanceApi
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.fun_mockapitest_3837 }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
```

It was generated by Visual Studio 2022.

**Comment by runceel** [comment]
The root cause of this error was disable Basic Authentication on Azure Functions' settings.
I enabled it, and the error was fixed.

**Comment by aarsan** [comment]
I'm facing the same issue. Azure Functions consumption plan and GitHub actions.

**Comment by yflement** [comment]
Running into the same issue although it worked last week, Python function with an Azure Functions consumption plan: 

```yaml
name: XYZ

on:
  push:
    branches: ["dev", "tst", "prd"]

env:
  AZURE_FUNCTIONAPP_NAME: 'our-app-name-${{ github.ref_name }}-location'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # Remove publish-profile to use Azure RBAC
        respect-funcignore: true
        scm-do-build-during-deployment: true
        enable-oryx-build: true
```

`AZURE_FUNCTIONAPP_NAME` resolves to `our-app-name-dev-location`
