### ISSUE TITLE
Deploy action is not deploying anything

### ISSUE THREAD

**Issue by alexbruno** [Azure/functions-action#192]
Deploy action is resolving as success but nothing is actually deployed.
The application is not working and by checking it at Azure through FTPS I see nothing in `/site/wwwroot/` dir, it is empty.

**Comment by patelchandni** [comment]
@alexbruno, I need more information to investigate.
1. Please share your .yaml workflow. 
2. Your function app is on which OS and SKU?
3. Is "package" parameter for this action pointing to right location?

**Comment by alexbruno** [comment]
Thanks for the response @patelchandni !
I'm not running any functions now, but I'm gonna run some new tests and give you feedback here in this thread.

**Comment by alexbruno** [comment]
I'm now able to deploy functions. Here are the steps I've used:
- Started a Function project with VSCode
- Sent it to GitHub (no deploy from VSCode Tools)
- Created a Function App at Azure Dashboard
- No CI/CD connection with my repo
- On Function App interface, I've got the Publish Profile (file download)
- On GitHub project secrets, I've put the content of the Publish Profile into a secret variable
- So, I've setup my GitHub CI/CD yml file with my application build
- Last step on my yml file is the `functions-action`:

```yml
      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        with:
          slot-name: Production
          app-name: ${{ env.APP_NAME }}
          package: ${{ env.PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PROFILE }}
```
