### ISSUE TITLE
Targeting branch for node20 support 

### ISSUE THREAD

**Issue by Julius-Bendt** [Azure/functions-action#231]
I'm trying to target the branch used in [this pr](https://github.com/Azure/functions-action/pull/229) (Updates - 229), in order to get node20 support. 

Is is a mistake that `action.yml` is pointing the main file to `lib/main.js` and not `src/main.js`?

I tried referencing the action by this branch, and got the following error:
`File not found: '/home/runner/work/_actions/Azure/functions-action/patelchandni/node20/lib/main.js'`

Steps:
```yaml
# (...)
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@patelchandni/node20
        id: fa
        with:
          app-name: 'name'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.xxxxx_PUBLISH_PROFILE }}
```
