### ISSUE TITLE
Flex Consumption deployment (Node Azure Functions App)

### ISSUE THREAD

**Issue by miszu** [Azure/functions-action#238]
I see that this PR by @patelchandni https://github.com/Azure/functions-action/pull/229 adds support for Flex Consumption plan of Azure Functions. I've tried deploying my Node Azure Function app to Flex Consumption with this yml actio:

```
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1.5.2
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        sku: flexconsumption
        remote-build: true
```

but this fails with:

```
Run Azure/functions-action@v1.5.2
  with:
    app-name: fitfunctionsapi
    package: .
    publish-profile: ***
    sku: flexconsumption
    remote-build: true
    respect-pom-xml: false
    respect-funcignore: false
    scm-do-build-during-deployment: false
    enable-oryx-build: false
  env:
    AZURE_FUNCTIONAPP_NAME: fitfunctionsapi
    AZURE_FUNCTIONAPP_PACKAGE_PATH: .
Successfully parsed SCM credential from publish-profile format.
Using SCM credential for authentication, GitHub Action will not perform resource validation.
Successfully acquired app settings from function app (with SCM credential)!
Will archive . into /home/runner/work/_temp/temp_web_package_3544899524961187.zip as function app content
Will use Kudu https://<scmsite>/api/publish to deploy since Flex consumption plan is detected.
Will use parameter remote-build: true
Package deployment using One Deploy initiated.
Starting deployment pipeline.
[ValidationStep] starting.
[AppSettingValidation] starting.
[DeploymentStorageValidation] starting.
Validation completed
[SourcePackageUriDownloadStep] starting.
Zip package is present at /tmp/zipdeploy/787287ed-8789-40f4-9f05-f9e150f41c70.zip
[ExtractZipStep] starting.
Cleaning files in /tmp/zipdeploy/extracted
Extracted zip package in /tmp/zipdeploy/extracted
[OryxBuildStep] starting.
Running oryx build command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 20.11.1
sh: 1: tsc: Permission denied
sh: 1: tsc: Permission denied\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 20.11.1
Failed during oryx build due to sh: 1: tsc: Permission denied\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 20.11.1
Deployment failed with Error: sh: 1: tsc: Permission denied\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 20.11.1
Error: Failed to deploy web package to Function App.
Error: Execution Exception (state: PublishContent) (step: Invocation)
Error:   When request Azure resource at PublishContent, oneDeploy : Failed to use /home/runner/work/_temp/temp_web_package_3544899524961187.zip as OneDeploy content
Error:     Package deployment using ZIP Deploy failed. Refer logs for more details.
Error: Deployment Failed!
```

Am I doing something wrong? I'd appreciate any help and would be happy to provide more logs/test solutions :)
