### ISSUE TITLE
Action continues when appname-slotname mismatches SCM credentials

### ISSUE THREAD

**Issue by Hazhzeng** [Azure/functions-action#25]
The function app will still be deployed to production when using SCM credentials even if the slot-name is set. Due to the limitation of the SCM credentials, the GitHub Action only have access to 1 site (either production or slot).
```
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: hazeng-fa-node-stage
        package: '.'
        publish-profile: ${{ secrets.SCM_CREDENTIALS }}
        slot-name: this-will-be-ignored
```
There's a way to mitigate this, that is to add a dash with slotname in the app-name, and use SCM_CREDENTIALS of the slot for deployment.
```
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: hazeng-fa-node-stage-slotnamehere
        package: '.'
        publish-profile: ${{ secrets.SCM_CREDENTIALS_OF_THE_SLOT }}
```
