### ISSUE TITLE
Switching to OIDC auth deletes all functions from functionapp for consumption plan

### ISSUE THREAD

**Issue by Quintisimo** [Azure/functions-action#268]
For a functionapp on consumption plan, I wanted to switch from using publish profile to oidc for addition security. Once I had updated the github action and ran the deploy it deleted all the functions in functionapp. Nothing shows up in the ui or the cli (az functionapp function list). Switching back to the publish profile fixes the issue.

Here is the github action job:
```
  deploy:
    if: github.actor != 'dependabot[bot]'
    needs: [get-repo-environments, deploy-infra, build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        environment: ${{ fromJson(needs.get-repo-environments.outputs.environments) }}
    environment: ${{ matrix.environment }}
    steps:
      - name: Download dist folder from artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID}}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Functions
        uses: azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
```
