### ISSUE TITLE
Deployment failing for flex-consumption plan

### ISSUE THREAD

**Issue by Quintisimo** [Azure/functions-action#275]
This morning the deployments to our functionapps started failing with this error:
```
Using RBAC for authentication, GitHub Action will perform resource validation.
Successfully acquired site configs from function app!
Detected function app sku: FlexConsumption
Successfully acquired app settings from function app (RBAC)!
Detected function app language: None (V1 function app)
Will archive . into /home/runner/work/_temp/temp_web_package_7456204418223658.zip as function app content
Will use Kudu https://<scmsite>/api/publish to deploy since Flex consumption plan is detected.
Will use parameter remote-build: true
Package deployment using One Deploy initiated.
Starting deployment pipeline.
[Kudu-SourcePackageUriDownloadStep] Skipping download. Zip package is present at /tmp/zipdeploy/5a5dfb70-a594-447f-8190-bf39817fd3e8.zip
[Kudu-ValidationStep] starting.
[Kudu-ValidationStep] completed.
[Kudu-ExtractZipStep] starting.
[Kudu-ExtractZipStep] completed.
[Kudu-ContentValidationStep] starting.
[Kudu-ContentValidationStep] completed.
[Kudu-PreBuildValidationStep] starting.
[Kudu-PreBuildValidationStep] completed.
[Kudu-OryxBuildStep] starting.
Input string was not in a correct format. Failure to parse near offset 40. Format item ends prematurely. More information: 
Error: Failed to deploy web package to Function App.
Error: Execution Exception (state: PublishContent) (step: Invocation)
Error:   When request Azure resource at PublishContent, oneDeploy : Failed to use /home/runner/work/_temp/temp_web_package_7456204418223658.zip as OneDeploy content
Error:     Package deployment using ZIP Deploy failed. Refer logs for more details.
Error: Deployment Failed!
```

Here is the github action yaml that deploys the function:
```yaml
- name: Download ${{ inputs.artifact-name }} file from artifacts
  uses: actions/download-artifact@v4
  with:
    name: ${{ inputs.artifact-name }}

- name: Log into Azure
  uses: azure/login@v2
  with:
    client-id: ${{ inputs.clientId }}
    tenant-id: ${{ inputs.tenantId }}
    subscription-id: ${{ inputs.subscriptionId }}

- name: Deploy Functions
  uses: azure/functions-action@v1
  with:
    app-name: ${{ inputs.app-name }}
    sku: flexconsumption
    remote-build: true
```
