### ISSUE TITLE
Action runs indefinitely on step Waiting for function app to spin up after app settings change

### ISSUE THREAD

**Issue by mikedouglasdev** [Azure/functions-action#31]
Hi,  I'm trying to use the Functions Action and it will run indefinitely on this step.  Here is the YAML.
```

name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: portalapi 
        # Directory containing files to upload
        path: /home/runner/work/portal-api/portal-api/FunctionApp1/bin/Release/netcoreapp3.1/bin/ng6users.api.dll
    - name: Azure Login  
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_AUTH }}
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.1.3
      with:
        # Name of the Azure Function App
        app-name: ghusersapi
        # Path to package or folder. *.zip or a folder to deploy
        package: /home/runner/work/portal-api/portal-api/FunctionApp1/bin/Release/netcoreapp3.1/bin/
```
Thanks,
Mike

**Comment by mikedouglasdev** [comment]
I'm not sure what change fixed it, but I followed the sample and got it working. 
https://github.com/Azure/actions-workflow-samples/blob/master/FunctionApp/linux-dotnet-functionapp-on-azure.yml

```
name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  AZURE_FUNCTIONAPP_NAME: ghusersapi  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.101'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    - name: Azure Login  
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_AUTH }}
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

```
