### ISSUE TITLE
Linux ElasticPremium plan is not yet supported

### ISSUE THREAD

**Issue by michal-halenka-datasentics** [Azure/functions-action#34]
The workflow working for Functions Consumption plan does not work for Functions Premium plan. 

Github Action step:
```
..............
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

    - name: 'Deploy Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}-${{ env.ENVIRONMENT }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
..............
```

Result:

```
Run Azure/functions-action@v1
##[Initialize]
##[ValidateParameter]
##[ValidateAzureResource]
Using RBAC for authentication, GitHub Action will perform resource validation.
Sucessfully acquired site configs from function app!
Detected function app sku: ElasticPremium
Sucessfully acquired app settings from function app (RBAC)!
Detected function app language: Python
##[error]Execution Exception (state: ValidateAzureResource) (step: ChangeContext)
##[error]  At ValidateAzureResource, Function Runtime : Linux ElasticPremium plan is not yet supported.
##[error]Deployment Failed!
```

**Comment by edouardr** [comment]
Hi,

I also have a Linux Function App running on Premium plan and managed to deployed successfully.

Below is my setup:

- I am not using RBAC Credentials but rather the publish profile
```yaml
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '.'
          publish-profile: ${{ secrets.SCM_PROD_CREDENTIALS }}
```

- Also, I needed to add the setting `WEBSITE_RUN_FROM_PACKAGE` with the value set to `1` in the configuration of my Function App

**Comment by edouardr** [comment]
To add to my previous comment, deployment was successful, however I can't see any function listed. It appears package was deployed but function app is not working as expected. Any idea?

**Comment by Duchynko** [comment]
I'm experiencing a similar problem after upgrading from the Dynamic Y1 to the Premium P1v2 tier. The deployment seems to be successful but I can't see any function listed, neither a new blob in my Storage Account. 

Initially, I set the `WEBSITE_RUN_FROM_PACKAGE` to an empty string (`""`).

This is my setup and I'm using RBAC.
```yml
- name: Deploy to Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: my-amazing-app
```
