### ISSUE TITLE
Respect .funcignore file rules

### ISSUE THREAD

**Issue by petyunchik** [Azure/functions-action#36]
Patterns of `.funcignore` file are ignored during deployment and everything is included under package folder. 
Would be nice to exclude files in accordance to `.funcignore` rules as it's implemented in [Azure Functions Core Tools](https://github.com/Azure/azure-functions-core-tools)

**Comment by petyunchik** [comment]
If someone looking for workaround try this:

```
    - name: Create Deployment Package
      shell: pwsh
      run: |
        npm install -g azure-functions-core-tools@3
        func pack

    - name: Deploy To Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: your-app-name
        package: ${{ github.event.repository.name }}.zip
```

It will create and deploy package using [Azure Functions Core Tools](https://github.com/Azure/azure-functions-core-tools), which respects rules from `.funcignore`

**Comment by aaronadamsCA** [comment]
Note the workaround does work, but it has to download the entire `azure-functions-core-tools` ZIP file on every run, which is also not ideal.

This is an official Azure action that includes a Node.js template. Out of the box, it was uploading 10.6 MB and then unpacking 10,000 files, when the actual function is a few files and a few kilobytes. Honestly, that's an inexcusable gap; it's basic functionality that should have been there for a 1.0 release.

**Comment by aksm-ms** [comment]
@N-Usha Can we mark this as an enhancement?

**Comment by maximivanov** [comment]
Here's a `rsync` trick I've used to exclude files listed in `.funcignore` from deployment. In your workflow file:

```yaml
...

env:
  ...
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  RELEASE_BUNDLE_PATH: 'release-bundle' # This is a new env var

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      ... checkout code, install, build ...

      # A new step to exclude files from deployment
      - name: Copy files to release bundle
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          rsync -av --prune-empty-dirs --exclude-from .funcignore ./ ${{ env.RELEASE_BUNDLE_PATH }}
          popd

      - name: Run Azure Functions action
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/${{ env.RELEASE_BUNDLE_PATH }}' 
          publish-profile: ....
```

But I agree with @aaronadamsCA it should work out of the box without any tricks.

Rsync solution works well but unfortunately I've hit another blocker which is files do not get removed from the Azure Function App instance when they're removed in code: https://github.com/Azure/functions-action/issues/33#issuecomment-739553637
