### ISSUE TITLE
Unable to deploy a linux typescript functionapp

### ISSUE THREAD

**Issue by jync** [Azure/functions-action#39]
Not entirely sure if this is where I should write the issue. Technically  not an issue of the action, but perhaps an underlying azure platform issue.

When I build and deploy my typescript functionapp, the deploy succeeds, but the function app is totally messed up. Here's what I've found.

1. Github action logs indicate deployment was successful:

```
##[Initialize]
##[ValidateParameter]
##[ValidateAzureResource]
Using SCM credential for authentication, GitHub Action will not perform resource validation.
Sucessfully acquired app settings from function app (SCM)!
##[PreparePublishContent]
Will directly deploy ./app/app.zip as function app content
Will use api/zipdeploy to deploy (scm credential)
##[PublishContent]
Setting SCM_DO_BUILD_DURING_DEPLOYMENT in Kudu container to false
Update using Client.updateAppSettingViaKudu
Response with status code 204
App setting SCM_DO_BUILD_DURING_DEPLOYMENT propagated to Kudu container
Setting ENABLE_ORYX_BUILD in Kudu container to false
Update using Client.updateAppSettingViaKudu
Response with status code 204
App setting ENABLE_ORYX_BUILD propagated to Kudu container
Package deployment using ZIP Deploy initiated.
Deploy logs can be viewed at https://app.scm.azurewebsites.net/api/deployments/<xxxxxx>/log
Successfully deployed web package to App Service.
Successfully updated deployment History at https://app.scm.azurewebsites.net/api/deployments/<xxxx>
```

2. When I navigate to the function app and click on functions, no functions are present
3. When I click on files, I can see the root files are there (host.json, package.json)
4. When I go to the storage area and download the zip file and try to expand it, it fails saying it is an unsupported format (I'm on a mac).

If I switch over to use azure function core tools and use that to publish the function, it works without issue.

**Comment by AmrutaKawade** [comment]
are you using consumption plan?

**Comment by jync** [comment]
Yes...

**Comment by AmrutaKawade** [comment]
You can check deployed files from Kudu Portal (Development Tools -> Advance Tools -> Go). On kudu portal under Tools -> Zip Push Deploy. You can view all the files

**Comment by Herlix** [comment]
I'm having the same problem. What I'm seeing is that I get WEBSITE_RUN_FROM_PACKAGE set to a URL when deploying with VScode+azure addons and the functions is there. This setup for github actions does not work. 
Yes I'm on consumption plan, linux app service.

**Comment by mathiasmaerker** [comment]
@AmrutaKawade I have the same issue and Kudu is not available for LInux and Consumption Plans. Any other way to check the uploaded package?

Regards 
Mathias

**Comment by komayama** [comment]
@AmrutaKawade 
I'm encountering same issue too. I checked Kudu the following deployment history (https://app.scm.azurewebsites.net/api/deployments/<xxxx>) in GitHub Actions.
`Deployment '<xxxx>' not found.`

Then I tried to put two app setting in Azure Function of Azure Portal. But It's was fail to deploy
- SCM_DO_BUILD_DURING_DEPLOYMENT: true
- ENABLE_ORYX_BUILD: true

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/24888431/100853066-aa4ad080-34ca-11eb-9fb7-ff05b83339d3.png)

I don't know is this GitHub Actions source support to remote deploy for Linux Consumption plan?
https://github.com/Azure/functions-action/blob/master/src/publishers/zipDeploy.ts

Best Regards
Kohei

**Comment by AmrutaKawade** [comment]
Currently only run from package deploy with url is supported for function apps with Linux Consumption Plan. https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#enabling-functions-to-run-from-a-package

check storage account linked to functionapp. ( appsettings -> AzureWebJobsStorage) you can find package in container of that storage account

**Comment by AmrutaKawade** [comment]
> @AmrutaKawade
> I'm encountering same issue too. I checked Kudu the following deployment history (https://app.scm.azurewebsites.net/api/deployments/) in GitHub Actions.
> `Deployment '<xxxx>' not found.`
> 
> Then I tried to put two app setting in Azure Function of Azure Portal. But It's was fail to deploy
> 
> * SCM_DO_BUILD_DURING_DEPLOYMENT: true
> * ENABLE_ORYX_BUILD: true
> 
> ![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/24888431/100853066-aa4ad080-34ca-11eb-9fb7-ff05b83339d3.png)
> 
> I don't know is this GitHub Actions source support to remote deploy for Linux Consumption plan?
> https://github.com/Azure/functions-action/blob/master/src/publishers/zipDeploy.ts
> 
> Best Regards
> Kohei

Remote Deploy is not supported currently

**Comment by komayama** [comment]
@AmrutaKawade 
I successfully deploy to Azure Functions using the following document and some app settings.
[Continuous delivery by using GitHub Action](https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-github-actions?tabs=javascript#build-the-function-app)

1. Add AppSettings in Azure Functions.

- ENABLE_ORYX_BUILD: true
- SCM_DO_BUILD_DURING_DEPLOYMENT: 1

> If Azure Functions AppSettings has ` WEBSITE_RUN_FROM_PACKAGE` element, remove that

2. Delete line about npm from GitHub Actions.
[Build the function app](https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-github-actions?tabs=javascript#build-the-function-app)

```
-    - name: 'Resolve Project Dependencies Using Npm'
-      shell: bash
-      run: |
-        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
-        npm install
-        npm run build --if-present
-        npm run test --if-present
-        popd
```

**Comment by komayama** [comment]
@AmrutaKawade 
When changed `SCM_DO_BUILD_DURING_DEPLOYMENT` value to `true` and `True`, there is only 8KiB file in scm-release of BLOB container. Maybe not build in Kudu. But change value to `1`, file size is 116 MiB.

![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/24888431/100968500-cc009200-3574-11eb-997f-ea906b6b5ec5.png)

**Comment by Renetnielsen** [comment]
Did anyone actually get this working yet? 
I more or less gave up doing CD deployment of a typescript app to azure from github.

It does not have any impact on how and what i do, it just wont work.

When i deploy from VScode everything is fine. 
When i use the script from https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-github-actions?tabs=javascript#build-the-function-app it just wont work.

My setup: 
Windows Function App on an App Service Plan (Not consumption).
Windows deployment script from the website
Typescript functions project

**Comment by mathiasmaerker** [comment]
@Renetnielsen I sort of got it to work, but it's just an workaround. I let the project build remotely, not sure if that does work for your use case

```
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}          

    - name: Install Azure Core Tools v3 for deployment
      run: npm i -g azure-functions-core-tools@3 --unsafe-perm true
    - name: Deploy to Azure
      run: func azure functionapp publish puppeteer-runner-fa --build remote
````

**Comment by maximivanov** [comment]
This Github Action works for me on Linux Consumption (I believe it worked on Linux Premium as well when I tested it couple months ago).

Here's the repo: https://github.com/maximivanov/azure-functions-cd-github-actions (funny enough it's to reproduce another bug https://github.com/Azure/functions-action/issues/62). It highlights a multi-target environment deployment technique I wanted to blog about.

FYI the App Settings generated with Terraform are:

<img width="930" alt="Screen Shot 2021-02-11 at 12 31 07" src="https://user-images.githubusercontent.com/1759643/107636818-1c772880-6c65-11eb-83c0-860ccb35f1ba.png">

**Comment by rubengarciam** [comment]
GitHub actions fails for me too. I have tried all the options listed above but none of them seem to work.

Stopping it first before deploying as listed in Azure/functions-action#26 didn't work either.

The original GitHub Workflow created by Azure:

```
# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - app

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run build --if-present
        npm run test --if-present
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 'app'
        slot-name: 'production'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
```
