### ISSUE TITLE
'Cannot read property 'toLowerCase' of undefined' during slot deployment

### ISSUE THREAD

**Issue by ianmccaul** [Azure/functions-action#67]
I am trying to deploy to a slot using the action. I am not using a publishing profile to deploy, but instead a service principal. Looking through the 'ParameterValidator.validateScmCredentialsSlotName' it looks like to do a slotted deployment you are requiring a profile? I am passing in a valid slot name that exists, so I am not sure why I would get this error. Help is appreciated.

**Comment by AmrutaKawade** [comment]
Deploying to slot using service principal is not supported currently

Check this issue https://github.com/Azure/functions-action/issues/65

**Comment by TimoWilhelm** [comment]
Could you please reconsider this? Not beeing able to do slot deployments using a service principal is a very frustrating.

In issue #65 you mentioned that

 > publish profile is more secure (limited priviledge)

but we can use granular RBAC assignments to control the permissions of the deployment service principal.

Also when deploying multiple apps (e.g. one webapp and one function app) we would need to track multiple publish profiles?
Using `azure/webapps-deploy@v2` works perfectly fine when deploying to a deployment slot, so this seems like an arbitrary limitation.

**Comment by katatohuk** [comment]
Agree that would be nice to implement, missing that feature so much

**Comment by crmitchelmore** [comment]
Yes, would like to see this feature also. 

An error message stating the above would have saved me time debugging too.

**Comment by ianmccaul** [comment]
> Yes, would like to see this feature also.
> 
> An error message stating the above would have saved me time debugging too.

Right... the error does not actually tell you the problem. Outside of being some arbitrary limitation.

**Comment by TimoWilhelm** [comment]
It's disappointing, that this scenario is not supported and the error messages are currently very misleading (you basically have to check the code to understand what's going on) but there is a workaround:

You can use the Azure/cli@v1.0.0 action to deploy a webapp (including function apps) to a slot while using a service principal.

Here is an example:
```
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Functions
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: |
            az webapp deployment source config-zip --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_FUNCTIONS_APPSERVICE }} --slot staging --src functions.zip

      - name: Swap Slots
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: |
            az webapp deployment slot swap --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_FUNCTIONS_APPSERVICE }} --slot staging --target-slot production

```
