### ISSUE TITLE
Add support for custom handlers in Linux consumption plans

### ISSUE THREAD

**Issue by NoNameProvided** [Azure/functions-action#81]
When I am attempting to deploy using this Action the deployment always fails. The same build can be deployed with the `func azure functionapp publish` command without any issue.

There are two different errors based on whether the `WEBSITE_RUN_FROM_PACKAGE` configuration option is set or not. We are using a Linux consumption plan, so when set it points to a blob storage containing the latest deployment zip. Obviously this option will be set after the first deployment so it should work in both cases.

<details>
<summary>Log when WEBSITE_RUN_FROM_PACKAGE is set</summary>

```
Run Azure/functions-action@v1
  with:
    app-name: func-REDACTED-staging-01
    package: ./build
    publish-profile: ***
    respect-funcignore: true
    respect-pom-xml: false
    scm-do-build-during-deployment: false
    enable-oryx-build: false
Successfully parsed SCM credential from old publish-profile format.
Using SCM credential for authentication, GitHub Action will not perform resource validation.
Sucessfully acquired app settings from function app (with SCM credential)!
Warning: The .funcignore file does not exist in your path ./build. Nothing will be changed.
Warning: The .funcignore file shares the same format as .gitignore. You can use it to exclude files from deployment.
Will archive ./build into /home/runner/work/_temp/temp_web_package_8964073453852144.zip as function app content
Will use Kudu https://<scmsite>/api/zipdeploy to deploy since publish-profile is detected.
Setting SCM_DO_BUILD_DURING_DEPLOYMENT in Kudu container to false
Update using Client.updateAppSettingViaKudu
Response with status code 204
App setting SCM_DO_BUILD_DURING_DEPLOYMENT propagated to Kudu container
Setting ENABLE_ORYX_BUILD in Kudu container to false
Update using Client.updateAppSettingViaKudu
Response with status code 204
App setting ENABLE_ORYX_BUILD propagated to Kudu container
Package deployment using ZIP Deploy initiated.
Error: Failed to deploy web package to App Service.
Successfully updated deployment History at func-REDACTED-staging-01.scm.azurewebsites.net/api/deployments/b5026f1058de8a11fedc3d0ef30729628f1c08011621435576470
Error: Execution Exception (state: PublishContent) (step: Invocation)
Error:   When request Azure resource at PublishContent, zipDeploy : Failed to use /home/runner/work/_temp/temp_web_package_8964073453852144.zip as ZipDeploy content
Error:     Failed to deploy web package to App Service.
Not Found (CODE: 404)
Error:       Error: Failed to deploy web package to App Service.
Not Found (CODE: 404)
    at Kudu.<anonymous> (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Kudu/azure-app-kudu-service.js:175:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Kudu/azure-app-kudu-service.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Deployment Failed!
```

</details>

<details>
<summary>Log when WEBSITE_RUN_FROM_PACKAGE is NOT set</summary>

```
Run Azure/functions-action@v1
  with:
    app-name: func-REDACTED-staging-01
    package: ./build
    publish-profile: ***
    respect-funcignore: true
    respect-pom-xml: false
    scm-do-build-during-deployment: false
    enable-oryx-build: false
Successfully parsed SCM credential from old publish-profile format.
Using SCM credential for authentication, GitHub Action will not perform resource validation.
Sucessfully acquired app settings from function app (with SCM credential)!
Warning: The .funcignore file does not exist in your path ./build. Nothing will be changed.
Warning: The .funcignore file shares the same format as .gitignore. You can use it to exclude files from deployment.
Will archive ./build into /home/runner/work/_temp/temp_web_package_7836364297632616.zip as function app content
Will use Kudu https://<scmsite>/api/zipdeploy to deploy since publish-profile is detected.
Error: Execution Exception (state: PublishContent) (step: Invocation)
Error:   When request Azure resource at PublishContent, zipDepoy : WEBSITE_RUN_FROM_PACKAGE in your function app is set to an URL. Please remove WEBSITE_RUN_FROM_PACKAGE app setting from your function app.
Error: Deployment Failed!
```

</details>

The relevant settings from the workflow file:
```yml
      - name: Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: func-REDACTED-staging-01
          package: ./build
          publish-profile: ${{ secrets.STAGING_PUBLISH_PROFILE }}
          respect-funcignore: true
```

The structure of my build folder:

```
func1-v1/
  - function.json
  - handler.js
func2-v1/
  - function.json
  - handler.js
shared/
node_modules/
  - <all required prod dependencies preinstalled before calling deployment>
host.json
local.settings.json
package.json
package-lock.json
```

What next steps can we take to solve this issue?

**Comment by kanika1894** [comment]
@NoNameProvided Can you please run the workflow in the debug mode (https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging) and mention the error that you are getting?

**Comment by dbanty** [comment]
I'm getting a similar error, though I'm not sure it's exactly the same. I have a Rust-based function created mostly by following the official tutorial. I'm trying to add CD via this action. I ran the action with debug as you requested above though I'm not sure what all is safe to share (or useful).

<details>
<summary>Error messages</summary>
```
Error: Execution Exception (state: PublishContent) (step: Invocation)
49
Error:   When request Azure resource at PublishContent, zipDepoy : WEBSITE_RUN_FROM_PACKAGE in your function app is set to an URL. Please remove WEBSITE_RUN_FROM_PACKAGE app setting from your function app.
50
Error: Deployment Failed!
```
</details>

<details>
<summary>Debug lines right before</summary>
```
##[debug][GET] ***.scm.azurewebsites.net/api/settings
##[debug]getAppSettings. Data: {"statusCode":200,"statusMessage":"OK","headers":{"transfer-encoding":"chunked","content-type":"application/json; charset=utf-8","server":"Kestrel","date":"Mon, 14 Jun 2021 01:47:27 GMT","connection":"close"},"body":{"deployment_branch":"master","SCM_TRACE_LEVEL":"Verbose","SCM_COMMAND_IDLE_TIMEOUT":"60","SCM_LOGSTREAM_TIMEOUT":"7200","SCM_BUILD_ARGS":"","SCM_USE_LIBGIT2SHARP_REPOSITORY":"0","AzureWebJobsDashboard":"***","AzureWebJobsStorage":"***","FUNCTIONS_EXTENSION_VERSION":"~1","WEBSITE_RUN_FROM_PACKAGE":"https://***.blob.core.windows.net/function-releases/20210613160207-114188c5-2edc-45e3-b7e4-fa9f72f9326b.zip?sv=2018-03-28&sr=b&sig=***&st=2021-06-13T15%3A57%3A09Z&se=2031-06-13T16%3A02%3A09Z&sp=r","WEBSITE_MOUNT_ENABLED":"1","ScmType":"None","WEBSITE_SITE_NAME":"***","WEBSITE_AUTH_ENABLED":"False","WEBSITE_SLOT_NAME":"Production","SCM_RUN_FROM_PACKAGE":"https://***.blob.core.windows.net/scm-releases/scm-latest-***.zip?sv=2014-02-14&sr=b&sig=***&se=2031-05-31T00%3A07%3A41Z&sp=rw","WEBSITE_AUTH_LOGOUT_PATH":"/.auth/logout","WEBSITE_AUTH_AUTO_AAD":"False"}}
##[debug]warmed up Kudu Service
```
</details>

And my workflow file looks like this:

```yaml
name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: rustup target add x86_64-unknown-linux-musl
      - run: cargo build --release --target=x86_64-unknown-linux-musl
      - run: mv target/x86_64-unknown-linux-musl/release/handler .
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ***
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          respect-funcignore: true
```

Hopefully this helps in resolving the issue, let me know if there's any more info that could be helpful!

**Comment by balag0** [comment]
@dbanty If you have the WEBSITE_RUN_FROM_PACKAGE app setting configured in your app, could you try removing / renaming it. 

Zipdeploy will overwrite the value for that appsetting, so the failing check could be to make sure you are ok losing the url configured in that appsetting.

**Comment by vicvarros** [comment]
@NoNameProvided I have no issues deploying my code on Linux consumption plans using this app settings:

`
 {
              "name": "AzureWebJobsStorage",
              "value": ...
            },
            {
              "name": "WEBSITE_NODE_DEFAULT_VERSION",
              "value": "~14"
            },
            {
              "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
              "value": ...
            },
            {
              "name": " FUNCTIONS_EXTENSION_VERSION",
              "value": "~3"
            },
            {
              "name": "FUNCTIONS_WORKER_RUNTIME",
              "value": "node"
            },
`

I use to deploy them with an ARM template and GitHub Actions, using this version `azure/functions-action@v1.4.0` and using Azure Service Principal for RBAC instead of using a publish profile.

`
      - uses: azure/functions-action@v1.4.0
        name: Deploy package to Azure Function Apps
        with:
          app-name: ${{ secrets.AZURE_FUNC_NAME }}
          package: ${{ github.workspace }}/code
`

**Comment by ss185427** [comment]
Steps to reproduce -

- Create an Azure Function in Go using instructions from [here](https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-other).
- Deploy on a **Linux Consumption plan** with Azure Functions Core Tools (via Azure Functions VS Code extension).
- Deployment works fine and Function also runs as expected at this point.

- Setup deployment using GitHub Actions using functions-action@v1.4.0
- Deployment fails from GitHub Actions with message - _Please remove WEBSITE_RUN_FROM_PACKAGE app setting from your function app_.
- Remove WEBSITE_RUN_FROM_PACKAGE from Function App Configuration, the deployment now succeeds in GitHub Actions.

Check Azure Function - 
```
Message
Error while assigning execute permission.
ExceptionMessage
Function not implemented [ENOSYS].
ExceptionType
Mono.Unix.UnixIOException

Message
Failed to start Worker Channel.
ExceptionMessage
Permission denied
ExceptionType
System.ComponentModel.Win32Exception
```

**Comment by bruno-ferreira-rma** [comment]
> Steps to reproduce -
> 
> * Create an Azure Function in Go using instructions from [here](https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-other).
> * Deploy on a **Linux Consumption plan** with Azure Functions Core Tools (via Azure Functions VS Code extension).
> * Deployment works fine and Function also runs as expected at this point.
> * Setup deployment using GitHub Actions using functions-action@v1.4.0
> * Deployment fails from GitHub Actions with message - _Please remove WEBSITE_RUN_FROM_PACKAGE app setting from your function app_.
> * Remove WEBSITE_RUN_FROM_PACKAGE from Function App Configuration, the deployment now succeeds in GitHub Actions.
> 
> Check Azure Function -
> 
> ```
> Message
> Error while assigning execute permission.
> ExceptionMessage
> Function not implemented [ENOSYS].
> ExceptionType
> Mono.Unix.UnixIOException
> 
> Message
> Failed to start Worker Channel.
> ExceptionMessage
> Permission denied
> ExceptionType
> System.ComponentModel.Win32Exception
> ```

I'm having the same issue from the default github action added from azure portal . Any news on a fix for this?

**Comment by balag0** [comment]
Looks like all these apps are using custom handlers. updated the title to reflect that to avoid confusion.

**Comment by ljtill** [comment]
Came across this issue too with my custom handler (Go), managed to get it working with the following workflow and appsettings...

```yaml
name: "Build & Deploy"

on:
  workflow_dispatch:

env:
  GO_VERSION: 1.17

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install"
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: "Build"
        run: |
          go build handler.go
      - name: "Upload"
        uses: actions/upload-artifact@v2
        with:
          name: handler
          path: ./handler
  deploy:
    name: "Deploy"
    runs-on: ubuntu-20.04
    needs: build
    strategy:
      matrix:
        include:
          - name: ""
            region: "uksouth"
          - name: ""
            region: "ukwest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Download"
        uses: actions/download-artifact@v2
        with:
          name: handler
      - name: "Login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
      - name: "Deploy"
        uses: azure/functions-action@v1
        with:
          app-name: ${{ matrix.name }}
          package: ${{ github.workspace }}
```

And these AppSettings on the function app...

```bicep
{
    name: 'FUNCTIONS_EXTENSION_VERSION'
    value: '~3'
}
{
    name: 'FUNCTIONS_WORKER_RUNTIME'
    value: 'custom'
}
{
    name: 'APPINSIGHTS_INSTRUMENTATIONKEY'
    value: insight.properties.InstrumentationKey
}
{
    name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
    value: insight.properties.ConnectionString
}
{
    name: 'AzureWebJobsStorage'
    value: 'DefaultEndpointsProtocol=https;AccountName=${account.name};AccountKey=${listKeys(account.id, account.apiVersion).keys[0].value};EndpointSuffix=${environment().suffixes.storage}'
}
```
