### ISSUE TITLE
Unable to deploy Python to a Linux Premium App

### ISSUE THREAD

**Issue by LoicH** [Azure/functions-action#92]
# Our workflow
I'm using Github actions to automatically deploy my production and staging Function Apps. My team is using Gitlab Flow, so we have a "master" branch (kind of a "dev" branch), which is then pushed to a "preproduction" branch, which is pushed to a "production" branch.

# My actions
I set up two actions, to deploy to my function apps every time there is a push on the "preproduction" or "production" branches.

I have a .github/workflows/preproduction-deploy.yml and .github/workflows/production-deploy.yml which contain:

## .github/workflows/preproduction-deploy.yml
```
name: Deploy on pre-production
on:
  push:
    branches:
      - preproduction


env:
  AZURE_FUNCTIONAPP_NAME: function-preprod
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'azure-functions/my-project' 
  PYTHON_VERSION: '3.8'             

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1.3.1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

```

## .github/workflows/production-deploy.yml

```
name: Déploiement OneDashboard en production
on:
  push:
    branches:
      - production

env:
  AZURE_FUNCTIONAPP_NAME: function-prod
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'azure-functions/my-project' 
  PYTHON_VERSION: '3.8'  

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1.3.1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.MY_PROJECT_PROD_FUNCTIONAPP_PUBLISH_PROFILE }}
```

# My problem

When I push on the "preproduction" branch, I see the action running, then when the action is done, I can check the App Files in the Portal, for my pre-production Function App, and I see the right code.

But when I push on the "production" branch, I see the action running, then succeeding, but the App Files do not reflect the right code. I see the same files that I deployed the time before, via Visual Studio Code.

- when I check the deployment logs, I see `"{\"type\":\"Deployment\",\"sha\":\"[the_correct_sha]\",\"repoName\":\"my_repo\",\"slotName\":\"production\"}"`, where `[the_correct_sha]` is the SHA of the last commit on "production"
- When I go to the Azure Portal > my production Function App > Deployment Center > Deployment Logs, the last deployment has the correct commit ID ([the_correct_sha]), but there is another deployment that was made previously with "Commit Author: N/A" and the commit ID is not a commit ID on my project.
